# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.2 on Thu Mar 28 17:26:44 2019
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.button_explore = wx.Button(self, wx.ID_ANY, "Extract and Explore")
        self.button_encode = wx.Button(self, wx.ID_ANY, "Encode and Repack")
        self.button_export = wx.Button(self, wx.ID_ANY, "Export New Module")
        self.button_delete = wx.Button(self, wx.ID_ANY, "Delete Temp Files (No Reencode)")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("Asset Manager")
        self.button_explore.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        mainsizer = wx.BoxSizer(wx.HORIZONTAL)
        vsizer = wx.BoxSizer(wx.VERTICAL)
        mainsizer.Add(self.button_explore, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        static_line_1 = wx.StaticLine(self, wx.ID_ANY, style=wx.LI_VERTICAL)
        mainsizer.Add(static_line_1, 0, wx.ALL | wx.EXPAND, 5)
        vsizer.Add(self.button_encode, 0, wx.ALL, 5)
        vsizer.Add(self.button_export, 0, wx.ALL, 5)
        mainsizer.Add(vsizer, 0, 0, 0)
        static_line_2 = wx.StaticLine(self, wx.ID_ANY, style=wx.LI_VERTICAL)
        mainsizer.Add(static_line_2, 0, wx.ALL | wx.EXPAND, 5)
        mainsizer.Add(self.button_delete, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        self.SetSizer(mainsizer)
        mainsizer.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyDialog
